name: Test

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-linux:

    runs-on: ubuntu-latest

    steps:
    #--------------------------------------------collect--------------------------------------------
    - uses: actions/checkout@v3
    
    - name: Collect dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc cmake -y
    
    - name: Setup build-aux
      run: |
        ./setup.sh
    
    #--------------------------------------------build--------------------------------------------
    - name: Build
      run : |
        mkdir -p build
        cd build
        cmake .. -DENABLE_EXTRA=ON -DENABLE_TEST=ON
        cmake --build .
    
    #--------------------------------------------test--------------------------------------------
    - name: Test
      run : |
        ctest --verbose
    
  test-macos:

    runs-on: macos-latest

    steps:
    #--------------------------------------------collect--------------------------------------------
    - uses: actions/checkout@v3
    
    - name: Collect dependencies
      run: |
        brew install cmake -y
    
    - name: Setup build-aux
      run : |
        ./setup.sh
    
    #--------------------------------------------build--------------------------------------------
    - name: Build
      run : |
        mkdir build
        cd build
        cmake .. -DENABLE_EXTRA=ON -DENABLE_TEST=ON
        cmake --build .
    
    #--------------------------------------------test--------------------------------------------
    - name: Test
      run : |
        ctest --verbose
